### ISSUE TITLE
sass in gulp file give me error

### ISSUE THREAD

**Issue by yehia67** [mor10/humescores#11]
After writting command glup in glup-dev directory..
it give me that:-
```

module.js:549
    throw err;
    ^
Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/lampp/htdocs/wordpress/wp-content/themes/gulp-dev/Gulpfile.js:10:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
I am using Ubuntu 18.04 in 64 bits machine

**Comment by sandeepkarmacharya** [comment]
Hi @yehia67 ,

I was also getting the same error message and tried installing all the dependencies manually but still, I was having different errors. So, I tried changing the content of package.json and deleted all the unnecessary content, thanks to "Learning NPM the Node Package Manager" course on Lynda. 

I am attaching the package.json file as a zip file. Please extract it and replace it with the original one. I hope this will work for you too.

Let me know if this works for you,
Thanks
[package.zip](https://github.com/mor10/humescores/files/2354476/package.zip)

**Comment by Neilisin** [comment]
This was helpful.  I ended up writing to Mor10 regarding this.

**Comment by TampaDave** [comment]
What worked for me was changing the gulp-sass version to 4.0.0 in your package.json file. There seems to be something that deprecated in Node 10 and the older version of gulp-sass that he had in his course file needed to be updated.  That worked for me. If you do this and still see issues, try updating the other module versions.  Good luck!

**Comment by yehia67** [comment]
Okay Thanks
